import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";
import pluginVue from "eslint-plugin-vue";


export default [
  {
    ignores: [
      ".nuxt/**",
      ".node_modules/**",
      ".vscode/**",
    ],
  },
  {files: ["**/*.{js,mjs,cjs,ts,vue}"]},
  {languageOptions: { globals: {...globals.browser, ...globals.node} }},
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  ...pluginVue.configs["flat/essential"],
  {files: ["**/*.vue"], languageOptions: {parserOptions: {parser: tseslint.parser}}},
  {
    rules: {
      "prefer-const": 2,
      curly: ["error", "multi"],
      "keyword-spacing": ["error", { before: true, after: true }],
      "space-before-blocks": ["error", "always"],
      "comma-spacing": ["error", { before: false, after: true }],
      "space-before-function-paren": [
        "error",
        { named: "never", anonymous: "never", asyncArrow: "ignore" },
      ],
      "arrow-spacing": ["error", { before: true, after: true }],
      "padded-blocks": ["error", "never"],
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-nested-ternary": "error",
      "no-unused-vars": "error",
      "no-undef": "off",
      eqeqeq: ["error", "smart"],
      "space-in-parens": ["error", "never"],
      "quote-props": ["error", "as-needed"],
      semi: ["error", "always"],
      "key-spacing": ["error", { beforeColon: false, afterColon: true }],
      "comma-style": ["error", "last"],
      "operator-linebreak": 0,
      "space-unary-ops": ["error", { words: false, nonwords: false }],
      "semi-spacing": ["error", { before: false, after: true }],
      "space-infix-ops": 2,
      camelcase: ["error", { properties: "always" }],
      "no-with": "error",
      "no-multi-str": "error",
      "linebreak-style": ["error", "windows"],
      quotes: ["error", "double", { allowTemplateLiterals: true }],
      indent: ["error", 2, { SwitchCase: 1 }],
      "no-mixed-spaces-and-tabs": "error",
      "no-trailing-spaces": "error",
      "comma-dangle": ["error", "always-multiline"],
      "no-spaced-func": "error",
      "brace-style": ["error", "1tbs", { allowSingleLine: true }],
      "max-len": ["warn", 150],
      "consistent-this": ["error", "self"],
      "dot-notation": ["error", { allowPattern: "^[a-z]+(_[a-z]+)+$" }],
      yoda: ["error", "never"],
      "no-tabs": "error",

    },
  },
  {
    files: ["*.vue"],
    rules: {
      "max-len": "off",
      "vue/max-len": [
        "warn",
        {
          code: 150,
          template: 150,
          ignoreStrings: true,
          ignoreTemplateLiterals: true,
        },
      ],
      "vue/no-parsing-error": "error",
      "vue/no-v-for-template-key": "error",
      "vue/no-arrow-functions-in-watch": "error",
      "vue/no-async-in-computed-properties": "error",
      "vue/no-child-content": "error",
      "vue/no-computed-properties-in-data": "error",
      "vue/no-custom-modifiers-on-v-model": "error",
      "vue/no-duplicate-attributes": "error",
      "vue/no-dupe-v-else-if": "error",
      "vue/no-dupe-keys": "error",
      "vue/no-reserved-component-names": "warn",
      "vue/no-reserved-props": "error",
      "vue/no-shared-component-data": "error",
      "vue/no-template-key": "error",
      "vue/no-textarea-mustache": "error",
      "vue/no-unused-components": "error",
      "vue/no-unused-vars": "error",
      "vue/no-use-computed-property-like-method": "error",
      "vue/no-use-v-if-with-v-for": "error",
      "vue/no-useless-template-attributes": "error",
      "vue/require-component-is": "error",
      "vue/require-prop-type-constructor": "error",
      "vue/require-render-return": "error",
      "vue/require-v-for-key": "error",
      "vue/require-valid-default-prop": "error",
      "vue/return-in-computed-property": "error",
      "vue/use-v-on-exact": "error",
      "vue/valid-attribute-name": "error",
      "vue/valid-model-definition": "error",
      "vue/valid-next-tick": "error",
      "vue/valid-template-root": "error",
      "vue/valid-v-bind-sync": "error",
      "vue/valid-v-bind": "error",
      "vue/valid-v-cloak": "error",
      "vue/valid-v-else-if": "error",
      "vue/valid-v-else": "error",
      "vue/valid-v-for": "error",
      "vue/valid-v-html": "error",
      "vue/valid-v-if": "error",
      "vue/valid-v-model": "error",
      "vue/valid-v-on": "error",
      "vue/valid-v-once": "error",
      "vue/valid-v-pre": "error",
      "vue/valid-v-show": "error",
      "vue/valid-v-slot": "error",
      "vue/valid-v-text": "error",
      "vue/component-definition-name-casing": ["error", "PascalCase"],
      "vue/html-end-tags": "error",
      "vue/first-attribute-linebreak": "error",
      "vue/html-indent": "error",
      "vue/html-quotes": "error",
      "vue/html-closing-bracket-newline": "error",
      "vue/html-closing-bracket-spacing": "error",
      "vue/html-self-closing": "error",
      "vue/max-attributes-per-line": [
        "error",
        { singleline: { max: 9999 }, multiline: { max: 1 } },
      ],
      "vue/mustache-interpolation-spacing": "error",
      "vue/no-multi-spaces": "error",
      "vue/no-spaces-around-equal-signs-in-attribute": "error",
      "vue/one-component-per-file": "error",
      "vue/prop-name-casing": "error",
      "vue/v-bind-style": "error",
      "vue/v-on-style": "error",
      "vue/this-in-template": "error",
      "vue/attributes-order": "error",
      "vue/no-lone-template": "error",
      "vue/block-order": "error",
      "vue/block-tag-newline": "error",
      "vue/no-duplicate-attr-inheritance": "error",
      "vue/no-empty-component-block": "error",
      "vue/no-potential-component-option-typo": "error",
      "vue/no-required-prop-with-default": "error",
      "vue/no-this-in-before-route-enter": "error",
      "vue/no-undef-components": "off",
      "vue/no-use-v-else-with-v-for": "error",
      "vue/no-useless-mustaches": "error",
      "vue/no-useless-v-bind": "error",
      "vue/padding-line-between-blocks": "error",
      "vue/prefer-separate-static-class": "error",
      "vue/prefer-true-attribute-shorthand": "error",
      "vue/require-direct-export": "error",
      "vue/no-v-text-v-html-on-component": "off",
      "vue/no-mutating-props": "warn",
      "vue/multi-word-component-names": "off",
    },
  },
];
